install:
	chmod +x eureka
	sudo cp eureka /usr/bin/
	sudo cp *.py /usr/bin/
	sudo cp *.pyc /usr/bin/
update:
	chmod +x eureka
	sudo cp eureka /usr/bin/
	sudo cp *.pyc /usr/bin/
	sudo cp *.py /usr/bin/
exec:
	chmod +x eureka
