install:
	chmod +x evreka
	sudo cp evreka /usr/bin/
	sudo cp *.py /usr/bin/
	sudo cp *.pyc /usr/bin/
update:
	rm /usr/bin/evreka
	rm /usr/bin/lex.*
	rm /usr/bin/parser.*
	rm /usr/bin/open_file.*
	chmod +x evreka
	sudo cp eureka /usr/bin/
	sudo cp *.pyc /usr/bin/
	sudo cp *.py /usr/bin/
exec:
	chmod +x evreka
