#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

# |-------------------------------| Evreka Programlama Dili |--------------------------------|
# Evreka, Python3 ile yazılmış, ve C koduna derlendikten sonra nesne koduna derlenen modülleri
# sayesinde yüksek performanslı, BASIC 'in benzer ve türkçe sözdizimli bir programlama dilidir
#
# Geliştirici: Eralp Çelebi

import os
import time
from sys import *
from openfile import *
from lex import *
from parser import alDEGISKEN,YERLESTIR,parser

symbols = {}

def run_shell():
    try:
        print("Evreka 0.4v GPL 3.0v(C) \n")
        while True:
            data = raw_input("<?>: ") + "\n<EOF>"
            open(".shell_data","w").write(data)
            toks = lex(data)
            parser(toks,0)
            ##print(symbols)
    except:
        print("\n")
        exit()

def run_file():
    data = openfile(argv[1])
    toks = lex(data)
    parser(toks,0)

if len(argv) == 2:
    run_file()
elif len(argv) == 1:
    run_shell()
else:
    print("HATA: ÇOK FAZLA ARGÜMAN GİRİLDİ")
